### ISSUE TITLE
导入postman无法安装,一直转圈,其他插件都可以安装

### ISSUE THREAD

**Issue by JaminYe** [eolinker/eoapi-extensions#42]

**Comment by scarqin** [comment]
@JaminYe 麻烦看一下控制台报错，给一下平台的信息

**Comment by JaminYe** [comment]
```
Error: Uncaught (in promise): TypeError: Invalid argument expected string
TypeError: Invalid argument expected string
    at V2 (967.fc842d9638ed0d01.js:1:1767188)
    at 967.fc842d9638ed0d01.js:1:1795544
    at 967.fc842d9638ed0d01.js:1:1795645
    at Generator.next (<anonymous>)
    at e (main.c6c4c9a16f0c10da.js:9:1744404)
    at c (main.c6c4c9a16f0c10da.js:9:1744606)
    at Q.invoke (polyfills.89288ca3c2b02591.js:1:8345)
    at Object.onInvoke (main.c6c4c9a16f0c10da.js:9:1003862)
    at Q.invoke (polyfills.89288ca3c2b02591.js:1:8283)
    at Rt.run (polyfills.89288ca3c2b02591.js:1:3603)
    at wt (polyfills.89288ca3c2b02591.js:1:17833)
    at polyfills.89288ca3c2b02591.js:1:16887
    at polyfills.89288ca3c2b02591.js:1:16996
    at e (main.c6c4c9a16f0c10da.js:9:1744439)
    at c (main.c6c4c9a16f0c10da.js:9:1744606)
    at Q.invoke (polyfills.89288ca3c2b02591.js:1:8345)
    at Object.onInvoke (main.c6c4c9a16f0c10da.js:9:1003862)
    at Q.invoke (polyfills.89288ca3c2b02591.js:1:8283)
    at Rt.run (polyfills.89288ca3c2b02591.js:1:3603)
    at polyfills.89288ca3c2b02591.js:1:18648
handleError @ main.c6c4c9a16f0c10da.js:9
next @ main.c6c4c9a16f0c10da.js:9
j.next @ main.c6c4c9a16f0c10da.js:9
P._next @ main.c6c4c9a16f0c10da.js:9
P.next @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
l @ main.c6c4c9a16f0c10da.js:9
g.next @ main.c6c4c9a16f0c10da.js:9
emit @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
invoke @ polyfills.89288ca3c2b02591.js:1
run @ polyfills.89288ca3c2b02591.js:1
runOutsideAngular @ main.c6c4c9a16f0c10da.js:9
onHandleError @ main.c6c4c9a16f0c10da.js:9
handleError @ polyfills.89288ca3c2b02591.js:1
runGuarded @ polyfills.89288ca3c2b02591.js:1
E.microtaskDrainDone @ polyfills.89288ca3c2b02591.js:1
A @ polyfills.89288ca3c2b02591.js:1
Promise.then（异步）
V @ polyfills.89288ca3c2b02591.js:1
M @ polyfills.89288ca3c2b02591.js:1
scheduleTask @ polyfills.89288ca3c2b02591.js:1
onScheduleTask @ polyfills.89288ca3c2b02591.js:1
scheduleTask @ polyfills.89288ca3c2b02591.js:1
scheduleTask @ polyfills.89288ca3c2b02591.js:1
scheduleMicroTask @ polyfills.89288ca3c2b02591.js:1
Wt @ polyfills.89288ca3c2b02591.js:1
wt @ polyfills.89288ca3c2b02591.js:1
（匿名） @ polyfills.89288ca3c2b02591.js:1
（匿名） @ polyfills.89288ca3c2b02591.js:1
Promise.then（异步）
（匿名） @ polyfills.89288ca3c2b02591.js:1
c @ polyfills.89288ca3c2b02591.js:1
N.then @ polyfills.89288ca3c2b02591.js:1
wt @ polyfills.89288ca3c2b02591.js:1
resolve @ polyfills.89288ca3c2b02591.js:1
e @ main.c6c4c9a16f0c10da.js:9
c @ main.c6c4c9a16f0c10da.js:9
invoke @ polyfills.89288ca3c2b02591.js:1
onInvoke @ main.c6c4c9a16f0c10da.js:9
invoke @ polyfills.89288ca3c2b02591.js:1
run @ polyfills.89288ca3c2b02591.js:1
（匿名） @ polyfills.89288ca3c2b02591.js:1
invokeTask @ polyfills.89288ca3c2b02591.js:1
onInvokeTask @ main.c6c4c9a16f0c10da.js:9
invokeTask @ polyfills.89288ca3c2b02591.js:1
runTask @ polyfills.89288ca3c2b02591.js:1
A @ polyfills.89288ca3c2b02591.js:1
Promise.then（异步）
V @ polyfills.89288ca3c2b02591.js:1
M @ polyfills.89288ca3c2b02591.js:1
scheduleTask @ polyfills.89288ca3c2b02591.js:1
onScheduleTask @ polyfills.89288ca3c2b02591.js:1
scheduleTask @ polyfills.89288ca3c2b02591.js:1
scheduleTask @ polyfills.89288ca3c2b02591.js:1
scheduleMicroTask @ polyfills.89288ca3c2b02591.js:1
Wt @ polyfills.89288ca3c2b02591.js:1
wt @ polyfills.89288ca3c2b02591.js:1
（匿名） @ polyfills.89288ca3c2b02591.js:1
（匿名） @ polyfills.89288ca3c2b02591.js:1
Promise.then（异步）
（匿名） @ polyfills.89288ca3c2b02591.js:1
c @ polyfills.89288ca3c2b02591.js:1
N.then @ polyfills.89288ca3c2b02591.js:1
wt @ polyfills.89288ca3c2b02591.js:1
resolve @ polyfills.89288ca3c2b02591.js:1
e @ main.c6c4c9a16f0c10da.js:9
c @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
c @ polyfills.89288ca3c2b02591.js:1
（匿名） @ main.c6c4c9a16f0c10da.js:9
fetchReadme @ 967.fc842d9638ed0d01.js:1
（匿名） @ 967.fc842d9638ed0d01.js:1
e @ main.c6c4c9a16f0c10da.js:9
c @ main.c6c4c9a16f0c10da.js:9
invoke @ polyfills.89288ca3c2b02591.js:1
onInvoke @ main.c6c4c9a16f0c10da.js:9
invoke @ polyfills.89288ca3c2b02591.js:1
run @ polyfills.89288ca3c2b02591.js:1
（匿名） @ polyfills.89288ca3c2b02591.js:1
invokeTask @ polyfills.89288ca3c2b02591.js:1
onInvokeTask @ main.c6c4c9a16f0c10da.js:9
invokeTask @ polyfills.89288ca3c2b02591.js:1
runTask @ polyfills.89288ca3c2b02591.js:1
A @ polyfills.89288ca3c2b02591.js:1
invokeTask @ polyfills.89288ca3c2b02591.js:1
Et @ polyfills.89288ca3c2b02591.js:1
rt @ polyfills.89288ca3c2b02591.js:1
Ct @ polyfills.89288ca3c2b02591.js:1
load（异步）
R.c @ polyfills.89288ca3c2b02591.js:1
scheduleTask @ polyfills.89288ca3c2b02591.js:1
onScheduleTask @ polyfills.89288ca3c2b02591.js:1
scheduleTask @ polyfills.89288ca3c2b02591.js:1
scheduleTask @ polyfills.89288ca3c2b02591.js:1
scheduleEventTask @ polyfills.89288ca3c2b02591.js:1
（匿名） @ polyfills.89288ca3c2b02591.js:1
（匿名） @ main.c6c4c9a16f0c10da.js:9
_._trySubscribe @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
l @ main.c6c4c9a16f0c10da.js:9
_.subscribe @ main.c6c4c9a16f0c10da.js:9
P @ main.c6c4c9a16f0c10da.js:9
j @ main.c6c4c9a16f0c10da.js:9
v._next @ main.c6c4c9a16f0c10da.js:9
P.next @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
_._trySubscribe @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
l @ main.c6c4c9a16f0c10da.js:9
_.subscribe @ main.c6c4c9a16f0c10da.js:9
i @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
l @ main.c6c4c9a16f0c10da.js:9
_.subscribe @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
l @ main.c6c4c9a16f0c10da.js:9
_.subscribe @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
l @ main.c6c4c9a16f0c10da.js:9
_.subscribe @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
c @ polyfills.89288ca3c2b02591.js:1
r @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
e @ main.c6c4c9a16f0c10da.js:9
c @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
c @ polyfills.89288ca3c2b02591.js:1
（匿名） @ main.c6c4c9a16f0c10da.js:9
requestDetail @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
e @ main.c6c4c9a16f0c10da.js:9
c @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
c @ polyfills.89288ca3c2b02591.js:1
（匿名） @ main.c6c4c9a16f0c10da.js:9
getDetail @ main.c6c4c9a16f0c10da.js:9
（匿名） @ 967.fc842d9638ed0d01.js:1
e @ main.c6c4c9a16f0c10da.js:9
c @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
c @ polyfills.89288ca3c2b02591.js:1
（匿名） @ main.c6c4c9a16f0c10da.js:9
getDetail @ 967.fc842d9638ed0d01.js:1
ngOnInit @ 967.fc842d9638ed0d01.js:1
je @ main.c6c4c9a16f0c10da.js:9
ve @ main.c6c4c9a16f0c10da.js:9
H @ main.c6c4c9a16f0c10da.js:9
sl @ main.c6c4c9a16f0c10da.js:9
uh @ main.c6c4c9a16f0c10da.js:9
sl @ main.c6c4c9a16f0c10da.js:9
dc @ main.c6c4c9a16f0c10da.js:9
W2 @ main.c6c4c9a16f0c10da.js:9
sl @ main.c6c4c9a16f0c10da.js:9
uh @ main.c6c4c9a16f0c10da.js:9
sl @ main.c6c4c9a16f0c10da.js:9
dc @ main.c6c4c9a16f0c10da.js:9
W2 @ main.c6c4c9a16f0c10da.js:9
sl @ main.c6c4c9a16f0c10da.js:9
hl @ main.c6c4c9a16f0c10da.js:9
detectChanges @ main.c6c4c9a16f0c10da.js:9
tick @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
invoke @ polyfills.89288ca3c2b02591.js:1
onInvoke @ main.c6c4c9a16f0c10da.js:9
invoke @ polyfills.89288ca3c2b02591.js:1
run @ polyfills.89288ca3c2b02591.js:1
run @ main.c6c4c9a16f0c10da.js:9
next @ main.c6c4c9a16f0c10da.js:9
j.next @ main.c6c4c9a16f0c10da.js:9
P._next @ main.c6c4c9a16f0c10da.js:9
P.next @ main.c6c4c9a16f0c10da.js:9
（匿名） @ main.c6c4c9a16f0c10da.js:9
l @ main.c6c4c9a16f0c10da.js:9
g.next @ main.c6c4c9a16f0c10da.js:9
emit @ main.c6c4c9a16f0c10da.js:9
U8 @ main.c6c4c9a16f0c10da.js:9
Tm @ main.c6c4c9a16f0c10da.js:9
onInvokeTask @ main.c6c4c9a16f0c10da.js:9
invokeTask @ polyfills.89288ca3c2b02591.js:1
runTask @ polyfills.89288ca3c2b02591.js:1
invokeTask @ polyfills.89288ca3c2b02591.js:1
Et @ polyfills.89288ca3c2b02591.js:1
rt @ polyfills.89288ca3c2b02591.js:1
Ct @ polyfills.89288ca3c2b02591.js:1
main.c6c4c9a16f0c10da.js:9 Error: Uncaught (in promise): Error: Error invoking remote method 'eo-sync': postcat-import-postman: No matching version found for postcat-import-postman@1.0.9.
Error: Error invoking remote method 'eo-sync': postcat-import-postman: No matching version found for postcat-import-postman@1.0.9.
    at a.invoke (node:electron/js2c/renderer_init:2:7610)
    at wt (polyfills.89288ca3c2b02591.js:1:17833)
    at polyfills.89288ca3c2b02591.js:1:16887
    at polyfills.89288ca3c2b02591.js:1:16996
    at e (main.c6c4c9a16f0c10da.js:9:1744439)
    at f (main.c6c4c9a16f0c10da.js:9:1744642)
    at Q.invoke (polyfills.89288ca3c2b02591.js:1:8345)
    at Object.onInvoke (main.c6c4c9a16f0c10da.js:9:1003862)
    at Q.invoke (polyfills.89288ca3c2b02591.js:1:8283)
    at Rt.run (polyfills.89288ca3c2b02591.js:1:3603)
    at polyfills.89288ca3c2b02591.js:1:18648
```
系统版本 macOS 12.6.5
Postcat版本  0.5.1

**Comment by scarqin** [comment]
修复啦，国内 cnpm 资源没有更新的问题
